name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -project TestPN.xcodeproj -scheme TestPN -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=13.2.2"
